/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "http": {
        "CREATE_SUCCESS": string;
        "UPDATE_SUCCESS": string;
        "DELETE_SUCCESS": string;
        "SERVICE_ERROR": string;
        "NOT_HAS": string;
        "NOT_DONE": string;
        "NOT_CLOSE": string;
        "NOT_DELETE": string;
        "NOT_ENABLE": string;
        "NOT_DISABLE": string;
        "NOT_ISSUE": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
